"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState,type FormEvent,type ReactNode} from "react";
import {supabase} from "@/lib/supabase";
import {getSupabaseErrorMessage} from "@/lib/supabaseErrors";
type Row=Record<string,unknown>;type Audience="All Residents"|"Specific Room"|"Specific Resident";type Priority="Low"|"Normal"|"Medium"|"High"|"Urgent";type FormStatus="Draft"|"Published"|"Cancelled"|"Active"|"Inactive";
type Notice={id:string;notice_number:string|null;title:string;description:string;notice_type:string|null;target_audience:string|null;audience:string|null;resident_id:string|null;room_id:string|null;priority:string|null;status:string|null;publish_date:string|null;expiry_date:string|null;is_active:boolean|null;pinned:boolean|null;show_as_popup:boolean|null;attachment_url:string|null;created_at:string;updated_at:string};
type FormState={title:string;description:string;notice_type:string;audience:Audience;resident_id:string;room_id:string;priority:Priority;status:FormStatus;publish_date:string;expiry_date:string;pinned:boolean;show_as_popup:boolean};
const categories=["General","Payment","Maintenance","Rules","Emergency","Announcement"],today=()=>new Date().toISOString().slice(0,10),blank=():FormState=>({title:"",description:"",notice_type:"General",audience:"All Residents",resident_id:"",room_id:"",priority:"Normal",status:"Draft",publish_date:today(),expiry_date:"",pinned:false,show_as_popup:false});
const inputClass="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100",text=(value:unknown)=>value==null?"":String(value),norm=(value:unknown)=>text(value).trim().toLowerCase(),first=(row:Row|undefined,keys:string[],fallback="-")=>keys.map(key=>text(row?.[key]).trim()).find(Boolean)||fallback;
const asAudience=(value:string|null):Audience=>["All Residents","Specific Room","Specific Resident"].includes(value||"")?value as Audience:"All Residents",asPriority=(value:string|null):Priority=>["Low","Normal","Medium","High","Urgent"].includes(value||"")?value as Priority:"Normal",asStatus=(value:string|null):FormStatus=>["Draft","Published","Cancelled","Active","Inactive"].includes(value||"")?value as FormStatus:"Draft";
export default function NoticesPage(){
 const[notices,setNotices]=useState<Notice[]>([]),[residents,setResidents]=useState<Row[]>([]),[rooms,setRooms]=useState<Row[]>([]),[form,setForm]=useState<FormState>(blank),[editing,setEditing]=useState<Notice|null>(null),[showForm,setShowForm]=useState(false),[search,setSearch]=useState(""),[filters,setFilters]=useState({status:"Current",category:"All",priority:"All",audience:"All",popup:"All"}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");const[n,r,m]=await Promise.all([supabase.from("notices").select("id,notice_number,title,description,notice_type,target_audience,audience,resident_id,room_id,priority,status,publish_date,expiry_date,is_active,pinned,show_as_popup,attachment_url,created_at,updated_at").order("pinned",{ascending:false}).order("publish_date",{ascending:false}),supabase.from("residents").select("id,full_name,status").order("full_name"),supabase.from("rooms").select("id,room_number,status").order("room_number")]),failed=n.error||r.error||m.error;if(failed)setError(getSupabaseErrorMessage(failed,"Notices could not be loaded."));else{setNotices((n.data??[])as Notice[]);setResidents((r.data??[])as Row[]);setRooms((m.data??[])as Row[])}setLoading(false)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer)},[refresh]);
 const options=useMemo(()=>({statuses:Array.from(new Set(["Draft","Published","Cancelled","Archived",...notices.map(n=>n.status).filter((v):v is string=>Boolean(v))])),categories:Array.from(new Set([...categories,...notices.map(n=>n.notice_type).filter((v):v is string=>Boolean(v))])),priorities:Array.from(new Set(["Low","Normal","High","Urgent",...notices.map(n=>n.priority).filter((v):v is string=>Boolean(v))]))}),[notices]);
 const filtered=useMemo(()=>notices.filter(notice=>{const resident=residents.find(r=>text(r.id)===notice.resident_id),room=rooms.find(r=>text(r.id)===notice.room_id),haystack=[notice.notice_number,notice.title,notice.description,notice.notice_type,notice.status,first(resident,["full_name"],""),first(room,["room_number"],"")].join(" ").toLowerCase();return(!search.trim()||haystack.includes(search.trim().toLowerCase()))&&(filters.status==="All Statuses"||(filters.status==="Current"?norm(notice.status)!=="archived":norm(notice.status)===norm(filters.status)))&&(filters.category==="All"||notice.notice_type===filters.category)&&(filters.priority==="All"||notice.priority===filters.priority)&&(filters.audience==="All"||notice.audience===filters.audience)&&(filters.popup==="All"||(filters.popup==="Popup"?notice.show_as_popup===true:!notice.show_as_popup))}),[filters,notices,residents,rooms,search]);
 function reset(){setForm(blank());setEditing(null)}
 function openEdit(notice:Notice){if(norm(notice.status)==="archived"){setError("Archived notices are read-only history.");return}setEditing(notice);setForm({title:notice.title||"",description:notice.description||"",notice_type:notice.notice_type||"General",audience:asAudience(notice.audience),resident_id:notice.resident_id||"",room_id:notice.room_id||"",priority:asPriority(notice.priority),status:asStatus(notice.status),publish_date:notice.publish_date||today(),expiry_date:notice.expiry_date||"",pinned:Boolean(notice.pinned),show_as_popup:Boolean(notice.show_as_popup)});setShowForm(true);setError("");setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");setMessage("");try{if(!form.title.trim()||!form.description.trim()||!form.publish_date)throw new Error("REQUIRED");if(form.expiry_date&&form.expiry_date<form.publish_date)throw new Error("DATE");let current:{id:string;status:string|null}|null=null;if(editing){const result=await supabase.from("notices").select("id,status").eq("id",editing.id).maybeSingle();current=result.data;if(result.error||!current||norm(current.status)==="archived")throw new Error("STALE")}if(form.audience==="Specific Resident"){if(!form.resident_id)throw new Error("RESIDENT");const result=await supabase.from("residents").select("id,status").eq("id",form.resident_id).maybeSingle(),changed=!editing||editing.resident_id!==form.resident_id;if(result.error||!result.data||(changed&&norm(result.data.status)==="archived"))throw new Error("RESIDENT")}if(form.audience==="Specific Room"){if(!form.room_id)throw new Error("ROOM");const result=await supabase.from("rooms").select("id").eq("id",form.room_id).maybeSingle();if(result.error||!result.data)throw new Error("ROOM")}
 const payload={title:form.title.trim(),description:form.description.trim(),notice_type:form.notice_type,target_audience:form.audience==="All Residents"?"All":form.audience==="Specific Room"?"Room":"Resident",audience:form.audience,resident_id:form.audience==="Specific Resident"?form.resident_id:null,room_id:form.audience==="Specific Room"?form.room_id:null,priority:form.priority,status:form.status,publish_date:form.publish_date,expiry_date:form.expiry_date||null,is_active:["Published","Active"].includes(form.status),pinned:form.pinned,show_as_popup:form.show_as_popup,updated_at:new Date().toISOString()};if(editing&&current){let query=supabase.from("notices").update(payload).eq("id",editing.id);query=current.status==null?query.is("status",null):query.eq("status",current.status);const result=await query.select("id").maybeSingle();if(result.error||!result.data)throw new Error("STALE")}else{const result=await supabase.from("notices").insert({...payload,notice_number:`NTC-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`});if(result.error)throw new Error("DATABASE")}setMessage(editing?"Notice updated successfully.":"Notice created successfully.");reset();setShowForm(false);await refresh()}catch(caught){const code=caught instanceof Error?caught.message:"",messages:Record<string,string>={REQUIRED:"Title, notice body, and publish date are required.",DATE:"Expiry date cannot be before publish date.",STALE:"This notice changed or was archived. Refresh and try again.",RESIDENT:"Select a valid, non-archived resident.",ROOM:"Select a valid room.",DATABASE:"The notice could not be saved."};setError(messages[code]||"The notice could not be saved.")}finally{setSaving(false)}}
 async function changeStatus(notice:Notice,next:"Draft"|"Published"|"Archived"){const verb=next==="Published"?"publish":next==="Draft"?"unpublish":"archive";if(!window.confirm(`Are you sure you want to ${verb} "${notice.title}"?`))return;setError("");setMessage("");const current=await supabase.from("notices").select("id,status").eq("id",notice.id).maybeSingle();if(current.error||!current.data||norm(current.data.status)==="archived"){setError("This notice changed or is already archived.");return}let query=supabase.from("notices").update({status:next,is_active:next==="Published",updated_at:new Date().toISOString()}).eq("id",notice.id);query=current.data.status==null?query.is("status",null):query.eq("status",current.data.status);const result=await query.select("id").maybeSingle();if(result.error||!result.data){setError("The notice status could not be changed.");return}if(editing?.id===notice.id){reset();setShowForm(false)}setMessage(next==="Archived"?"Notice archived; its history is preserved.":`Notice ${next==="Published"?"published":"unpublished"}.`);await refresh()}
 const setFilter=(key:keyof typeof filters,value:string)=>setFilters(current=>({...current,[key]:value}));
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><section className="flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-600">StayHub</p><h1 className="mt-2 text-3xl font-bold">Notices</h1><p className="mt-1 text-sm text-slate-500">Create, publish, target, review, and preserve hostel notices.</p></div><button type="button" onClick={()=>{reset();setShowForm(true);setError("");setMessage("")}} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">+ Add Notice</button></section>
 {(message||error)&&<p className={`rounded-2xl border p-4 text-sm font-medium ${error?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error||message}</p>}
 {showForm&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{editing?"Edit Notice":"New Notice"}</h2><button type="button" onClick={()=>{reset();setShowForm(false)}} className="rounded-lg border px-3 py-2 text-sm">Close</button></div><form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
 <Field label="Title *" wide><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={inputClass}/></Field><Field label="Notice Body / Message *" wide><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className={`${inputClass} min-h-32`}/></Field><Field label="Category / Type"><Select value={form.notice_type} onChange={value=>setForm({...form,notice_type:value})} options={options.categories}/></Field><Field label="Audience"><Select value={form.audience} onChange={value=>setForm({...form,audience:value as Audience,resident_id:"",room_id:""})} options={["All Residents","Specific Room","Specific Resident"]}/></Field>
 {form.audience==="Specific Resident"&&<Field label="Resident *"><select required value={form.resident_id} onChange={e=>setForm({...form,resident_id:e.target.value})} className={inputClass}><option value="">Select resident</option>{residents.filter(r=>text(r.id)===form.resident_id||norm(r.status)!=="archived").map(r=><option key={text(r.id)} value={text(r.id)}>{first(r,["full_name"])}</option>)}</select></Field>}{form.audience==="Specific Room"&&<Field label="Room *"><select required value={form.room_id} onChange={e=>setForm({...form,room_id:e.target.value})} className={inputClass}><option value="">Select room</option>{rooms.map(r=><option key={text(r.id)} value={text(r.id)}>{first(r,["room_number"])}</option>)}</select></Field>}
 <Field label="Priority"><Select value={form.priority} onChange={value=>setForm({...form,priority:value as Priority})} options={["Low","Normal",...(form.priority==="Medium"?["Medium"]:[]),"High","Urgent"]}/></Field><Field label="Status"><Select value={form.status} onChange={value=>setForm({...form,status:value as FormStatus})} options={["Draft","Published","Cancelled",...(editing&&["Active","Inactive"].includes(editing.status||"")?[editing.status as string]:[])]}/></Field><Field label="Publish Date *"><input required type="date" value={form.publish_date} onChange={e=>setForm({...form,publish_date:e.target.value})} className={inputClass}/></Field><Field label="Expiry Date"><input type="date" value={form.expiry_date} onChange={e=>setForm({...form,expiry_date:e.target.value})} className={inputClass}/></Field><Toggle checked={form.pinned} set={value=>setForm({...form,pinned:value})} label="Pin in notices list"/><Toggle checked={form.show_as_popup} set={value=>setForm({...form,show_as_popup:value})} label="Show as Resident Portal popup"/><div className="md:col-span-2 xl:col-span-3"><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving...":editing?"Update Notice":"Save Notice"}</button></div></form></section>}
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search notices" className={`${inputClass} xl:col-span-2`}/><Select value={filters.status} onChange={value=>setFilter("status",value)} options={["Current","All Statuses",...options.statuses]}/><Select value={filters.category} onChange={value=>setFilter("category",value)} options={["All",...options.categories]}/><Select value={filters.priority} onChange={value=>setFilter("priority",value)} options={["All",...options.priorities]}/><Select value={filters.audience} onChange={value=>setFilter("audience",value)} options={["All","All Residents","Specific Room","Specific Resident"]}/><Select value={filters.popup} onChange={value=>setFilter("popup",value)} options={["All","Popup","Standard"]}/></div></section>
 <section className="grid gap-5 lg:grid-cols-2">{loading?<Empty value="Loading notices..."/>:filtered.length===0?<Empty value="No notices found."/>:filtered.map(notice=>{const resident=residents.find(r=>text(r.id)===notice.resident_id),room=rooms.find(r=>text(r.id)===notice.room_id),expired=Boolean(notice.expiry_date&&notice.expiry_date<today()),archived=norm(notice.status)==="archived",published=norm(notice.status)==="published";return <article key={notice.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2 text-xs font-bold uppercase text-indigo-600">{notice.pinned&&<span>Pinned</span>}{notice.show_as_popup&&<span>Popup</span>}</div><h2 className="mt-1 text-xl font-bold">{notice.title}</h2><p className="mt-1 text-xs text-slate-500">{notice.notice_number||notice.id}</p></div><div className="flex flex-wrap gap-2"><Badge value={notice.notice_type||"General"}/><Badge value={notice.priority||"Normal"}/><Badge value={expired?"Expired":notice.status||"Draft"}/></div></div><p className="mt-4 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{notice.description}</p><div className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 text-sm sm:grid-cols-2"><Info label="Audience" value={notice.audience||notice.target_audience||"-"}/>{notice.resident_id&&<Info label="Resident" value={first(resident,["full_name"])}/>} {notice.room_id&&<Info label="Room" value={first(room,["room_number"])}/>}<Info label="Publish Date" value={notice.publish_date||"-"}/><Info label="Expiry Date" value={notice.expiry_date||"No expiry"}/><Info label="Popup" value={notice.show_as_popup?"Enabled":"Disabled"}/></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/notices/${notice.id}`} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold">View</Link>{!archived&&<button type="button" onClick={()=>openEdit(notice)} className="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-semibold text-indigo-700">Edit</button>}{!archived&&<button type="button" onClick={()=>void changeStatus(notice,published?"Draft":"Published")} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-semibold text-emerald-700">{published?"Unpublish":"Publish"}</button>}{!archived&&<button type="button" onClick={()=>void changeStatus(notice,"Archived")} className="rounded-lg border border-amber-200 px-3 py-2 text-xs font-semibold text-amber-800">Archive</button>}</div></article>})}</section></div></main>
}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:ReactNode}){return <label className={wide?"md:col-span-2 xl:col-span-3":""}><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>}
function Select({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:string[]}){return <select value={value} onChange={e=>onChange(e.target.value)} className={inputClass}>{Array.from(new Set(options)).map(option=><option key={option}>{option}</option>)}</select>}
function Toggle({checked,set,label}:{checked:boolean;set:(value:boolean)=>void;label:string}){return <label className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><span className="text-sm font-semibold">{label}</span></label>}
function Badge({value}:{value:string}){return <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{value}</span>}
function Info({label,value}:{label:string;value:string}){return <p><span className="font-semibold text-slate-800">{label}:</span> {value}</p>}
function Empty({value}:{value:string}){return <p className="rounded-3xl bg-white p-10 text-center text-slate-500 lg:col-span-2">{value}</p>}
